accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from .views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from .views import (
    ReceiptCreateView,
    CategoryCreateView,
    AccountCreateView,
    ReceiptListView,
    CategoryListView,
    AccountListView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "create/",
        ReceiptCreateView.as_view(),
        name="receipt_create",
    ),
    path(
        "categories/create/",
        CategoryCreateView.as_view(),
        name="category_create",
    ),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="account_create",
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from re import T
from django.db import models
from django.conf import settings
from django.forms import DateTimeField, DecimalField

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3, null=True)
    tax = models.DecimalField(max_digits=10, decimal_places=3, null=True)
    date = models.DateField(null=True)
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.vendor

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=raw_password)
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from unicodedata import category
from django.shortcuts import render, redirect
from django.views.generic import ListView, TemplateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Account, Receipt, ExpenseCategory
from django.urls import reverse_lazy
from .form import ReceiptForm


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)

    # login_url = "/login/"
    # redirect_field_name = "home"


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    form_class = ReceiptForm

    def get_form_kwargs(self):
        kwargs = super(ReceiptCreateView, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        receipt = form.save(commit=False)
        receipt.purchaser = self.request.user
        receipt.save()
        form.save_m2m()
        return redirect("home")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        account = form.save(commit=False)
        account.owner = self.request.user
        account.save()
        return redirect("account_list")

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        category = form.save(commit=False)
        category.owner = self.request.user
        category.save()
        return redirect("category_list")


class CategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Expenses</title>
</head>
<body>
    <header>
        <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'home' %}">Receipts</a>
            </li>
            <li>
                <a href="{% url 'receipt_create' %}">Create receipt</a>
            </li>
            <li>
                <a href="{% url 'account_list' %}">Accounts</a>
            </li>
            <li>
                <a href="{% url 'account_create' %}">Create account</a>
            </li>
            <li>
                <a href="{% url 'category_list' %}">Categories</a>
            </li>
            <li>
                <a href="{% url 'category_create' %}">Create category</a>
            </li>
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'signup' %}">Sign Up</a>
            </li>
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>  
            {% endif %} 
        </ul>
        </nav>
    </header>
    <main>
    {% block content %}
    {% endblock content %}
    </main>    
</body>
</html>

receipts/templates/receipts/accounts/create.html
{% extends 'base.html' %}


{% block content %}
<main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button>Create</button>
      </div>
    </form>
  </main>
{% endblock content%}

receipts/templates/receipts/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Accounts</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for account in account_list %}
        <tr>
            <td>{{ account.name }}</td>
            <td>{{ account.number }}</td>
            <td>{{ account.receipts.all | length }}</td>
        </tr>
        {% endfor %}    
    </tbody>
</table>



{% endblock content %}

receipts/templates/receipts/categories/create.html
{% extends 'base.html' %}


{% block content %}
<main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button>Create</button>
      </div>
    </form>
  </main>
{% endblock content%}

receipts/templates/receipts/categories/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Expense Category</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for category in expensecategory_list %}
        <tr>
            <td>{{ category.name }}</td>
            <td>{{ category.receipts.all | length }}</td>
        </tr>
        {% endfor %}    
    </tbody>
</table>



{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}


{% block content %}
<main>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button>Create</button>
      </div>
    </form>
  </main>
{% endblock content%}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Receipts</h1>
<table>
    <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
    </thead>
    <tbody>
        {% for receipt in receipt_list %}
        <tr>
            <td>{{ receipt.vendor }}</td>
            <td>{{ receipt.total }}</td>
            <td>{{ receipt.tax }}</td>
            <td>{{ receipt.date }}</td>
            <td>{{ receipt.category }}</td>
            {% if receipt.accounts|length == 0 %}
                <td>Cash</td>
            {%else %}
                <td>{{ receipt.account }}</td>
            {% endif %}
        </tr>
        {% endfor %}    
    </tbody>
</table>



{% endblock content %}